# -*- coding: utf-8 -*-
"""MultiClassification_DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16y20p1PYMoEtLgPWOAdM32EkIGaBW1JA
"""



import tensorflow as tf

minst=tf.keras.datasets.mnist
(X_train,Y_train),(X_test,Y_test)=minst.load_data()
X_train=tf.keras.utils.normalize(X_train,axis=1)
X_test=tf.keras.utils.normalize(X_test,axis=1)

import matplotlib.pyplot as plt
plt.imshow(X_train[19])

model=tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28,28)),
        tf.keras.layers.Dense(120,activation=tf.nn.relu),
        tf.keras.layers.Dense(120,activation=tf.nn.relu),
        tf.keras.layers.Dropout(rate=0.2),
        tf.keras.layers.Dense(10,activation='softmax')
    ]
)
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

earlystop=tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True,
    verbose=2
  )

model.fit(
    X_train,
    Y_train,
    validation_split=0.2,
    epochs=300,
     callbacks=[earlystop])

model.evaluate(X_test,  Y_test, verbose=4)









